export { BsDashCircleFill } from "react-icons/bs";
export { IoIosAddCircleOutline } from "react-icons/io";
export { PiCurrencyNgn } from "react-icons/pi";
export { GoHeart } from "react-icons/go";
export { GoHeartFill } from "react-icons/go";
// export { PiCurrencyNgn } from "react-icons/pi";
export { HiStar } from "react-icons/hi2";
export { IoChevronForwardOutline, IoChevronBackOutline } from "react-icons/io5";
export { IoLogoInstagram } from "react-icons/io5";
export { FaFacebook, FaRegCheckCircle, } from "react-icons/fa";
export { FaPlus, FaCheck } from "react-icons/fa6";
export { IoIosAddCircle } from "react-icons/io";
export { PiShoppingCartBold } from "react-icons/pi";
export { TbBus } from "react-icons/tb";
export { BsBoxSeam } from "react-icons/bs";
export { MdEdit } from "react-icons/md";
export { PiShareBold } from "react-icons/pi";
export { FiSearch } from "react-icons/fi";
export { IoIosArrowDown } from "react-icons/io";
export { TiPlus } from "react-icons/ti";
export { VscCircleFilled } from "react-icons/vsc";
export { FiXCircle } from "react-icons/fi";
